CREATE TABLE password_recoveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    expira_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    verificado_em TIMESTAMP(6) WITHOUT TIME ZONE,
    usado_em TIMESTAMP(6) WITHOUT TIME ZONE,
    tentativas INTEGER NOT NULL DEFAULT 0,
    recovery_token_hash VARCHAR(64),
    recovery_token_expira_em TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_password_recoveries_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_password_recoveries_tentativas CHECK (tentativas >= 0)
);

CREATE INDEX idx_password_recoveries_usuario_criado
    ON password_recoveries (usuario_id, criado_em DESC);

CREATE INDEX idx_password_recoveries_ativo_expiracao
    ON password_recoveries (usuario_id, usado_em, expira_em);

CREATE UNIQUE INDEX uk_password_recoveries_token_hash
    ON password_recoveries (recovery_token_hash)
    WHERE recovery_token_hash IS NOT NULL;
