CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo_funcao VARCHAR(80) NOT NULL,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    email VARCHAR(160) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    perfil VARCHAR(20) NOT NULL,
    senha VARCHAR(20) NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_perfil CHECK (perfil IN ('FUNCIONARIO', 'GESTOR'))
);

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo BOOLEAN NOT NULL,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    documento VARCHAR(30),
    email VARCHAR(160),
    endereco VARCHAR(255),
    nome VARCHAR(120) NOT NULL,
    telefone VARCHAR(30),
    gestor_id BIGINT NOT NULL,
    CONSTRAINT fk_clientes_gestor FOREIGN KEY (gestor_id) REFERENCES usuarios (id)
);

CREATE TABLE fornecedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo BOOLEAN NOT NULL,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    documento VARCHAR(30),
    email VARCHAR(160),
    endereco VARCHAR(255),
    nome VARCHAR(120) NOT NULL,
    telefone VARCHAR(30),
    gestor_id BIGINT NOT NULL,
    CONSTRAINT fk_fornecedores_gestor FOREIGN KEY (gestor_id) REFERENCES usuarios (id)
);

CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo BOOLEAN NOT NULL,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    descricao VARCHAR(500),
    estoque_atual NUMERIC(12,3) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    preco_venda NUMERIC(12,2) NOT NULL,
    unidade_medida VARCHAR(30) NOT NULL,
    gestor_id BIGINT NOT NULL,
    CONSTRAINT fk_produtos_gestor FOREIGN KEY (gestor_id) REFERENCES usuarios (id)
);

CREATE TABLE materias_primas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo BOOLEAN NOT NULL,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    custo_medio NUMERIC(12,2) NOT NULL,
    descricao VARCHAR(500),
    estoque_atual NUMERIC(12,3) NOT NULL,
    estoque_minimo NUMERIC(12,3) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    unidade_medida VARCHAR(30) NOT NULL,
    gestor_id BIGINT NOT NULL,
    CONSTRAINT fk_materias_primas_gestor FOREIGN KEY (gestor_id) REFERENCES usuarios (id)
);

CREATE TABLE lancamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atualizado_em TIMESTAMP(6) WITHOUT TIME ZONE,
    cliente_ou_fornecedor VARCHAR(120),
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    data_lancamento DATE NOT NULL,
    data_vencimento DATE,
    descricao VARCHAR(500),
    forma_pagamento VARCHAR(30),
    nome_produto_ou_insumo VARCHAR(120),
    quantidade NUMERIC(12,3),
    status_pagamento VARCHAR(30) NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    titulo VARCHAR(180) NOT NULL,
    unidade_medida VARCHAR(30),
    valor_total NUMERIC(12,2) NOT NULL,
    gestor_id BIGINT NOT NULL,
    CONSTRAINT fk_lancamentos_gestor FOREIGN KEY (gestor_id) REFERENCES usuarios (id),
    CONSTRAINT ck_lancamentos_forma_pagamento CHECK (forma_pagamento IS NULL OR forma_pagamento IN ('BOLETO', 'CARTAO', 'DINHEIRO', 'OUTRO', 'PIX')),
    CONSTRAINT ck_lancamentos_status_pagamento CHECK (status_pagamento IN ('ATRASADO', 'NAO_SE_APLICA', 'PAGO', 'PENDENTE')),
    CONSTRAINT ck_lancamentos_tipo CHECK (tipo IN ('COMPRA_PRODUTO', 'GASTO_GERAL', 'PRODUCAO', 'VENDA'))
);

CREATE TABLE vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    data_venda DATE NOT NULL,
    forma_pagamento VARCHAR(30),
    observacao VARCHAR(500),
    status_pagamento VARCHAR(30) NOT NULL,
    valor_total NUMERIC(12,2) NOT NULL,
    cliente_id BIGINT,
    gestor_id BIGINT NOT NULL,
    CONSTRAINT fk_vendas_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id),
    CONSTRAINT fk_vendas_gestor FOREIGN KEY (gestor_id) REFERENCES usuarios (id),
    CONSTRAINT ck_vendas_forma_pagamento CHECK (forma_pagamento IS NULL OR forma_pagamento IN ('BOLETO', 'CARTAO', 'DINHEIRO', 'OUTRO', 'PIX')),
    CONSTRAINT ck_vendas_status_pagamento CHECK (status_pagamento IN ('ATRASADO', 'NAO_SE_APLICA', 'PAGO', 'PENDENTE'))
);

CREATE TABLE itens_venda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade NUMERIC(12,3) NOT NULL,
    valor_total NUMERIC(12,2) NOT NULL,
    valor_unitario NUMERIC(12,2) NOT NULL,
    produto_id BIGINT NOT NULL,
    venda_id BIGINT NOT NULL,
    CONSTRAINT fk_itens_venda_produto FOREIGN KEY (produto_id) REFERENCES produtos (id),
    CONSTRAINT fk_itens_venda_venda FOREIGN KEY (venda_id) REFERENCES vendas (id)
);

CREATE TABLE compras_materias_primas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    data_compra DATE NOT NULL,
    forma_pagamento VARCHAR(30),
    observacao VARCHAR(500),
    status_pagamento VARCHAR(30) NOT NULL,
    valor_total NUMERIC(12,2) NOT NULL,
    fornecedor_id BIGINT,
    gestor_id BIGINT NOT NULL,
    CONSTRAINT fk_compras_materias_primas_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES fornecedores (id),
    CONSTRAINT fk_compras_materias_primas_gestor FOREIGN KEY (gestor_id) REFERENCES usuarios (id),
    CONSTRAINT ck_compras_forma_pagamento CHECK (forma_pagamento IS NULL OR forma_pagamento IN ('BOLETO', 'CARTAO', 'DINHEIRO', 'OUTRO', 'PIX')),
    CONSTRAINT ck_compras_status_pagamento CHECK (status_pagamento IN ('ATRASADO', 'NAO_SE_APLICA', 'PAGO', 'PENDENTE'))
);

CREATE TABLE itens_compra_materia_prima (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade NUMERIC(12,3) NOT NULL,
    valor_total NUMERIC(12,2) NOT NULL,
    valor_unitario NUMERIC(12,2) NOT NULL,
    compra_id BIGINT NOT NULL,
    materia_prima_id BIGINT NOT NULL,
    CONSTRAINT fk_itens_compra_materia_prima_compra FOREIGN KEY (compra_id) REFERENCES compras_materias_primas (id),
    CONSTRAINT fk_itens_compra_materia_prima_materia_prima FOREIGN KEY (materia_prima_id) REFERENCES materias_primas (id)
);

CREATE TABLE producoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    custo_estimado NUMERIC(12,2) NOT NULL,
    data_producao DATE NOT NULL,
    observacao VARCHAR(500),
    quantidade_produzida NUMERIC(12,3) NOT NULL,
    gestor_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    CONSTRAINT fk_producoes_gestor FOREIGN KEY (gestor_id) REFERENCES usuarios (id),
    CONSTRAINT fk_producoes_produto FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE TABLE itens_producao_materia_prima (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custo_total NUMERIC(12,2) NOT NULL,
    custo_unitario NUMERIC(12,2) NOT NULL,
    quantidade_utilizada NUMERIC(12,3) NOT NULL,
    materia_prima_id BIGINT NOT NULL,
    producao_id BIGINT NOT NULL,
    CONSTRAINT fk_itens_producao_materia_prima_materia_prima FOREIGN KEY (materia_prima_id) REFERENCES materias_primas (id),
    CONSTRAINT fk_itens_producao_materia_prima_producao FOREIGN KEY (producao_id) REFERENCES producoes (id)
);

CREATE TABLE insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    mensagem VARCHAR(1000) NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    titulo VARCHAR(180) NOT NULL,
    gestor_id BIGINT NOT NULL,
    CONSTRAINT fk_insights_gestor FOREIGN KEY (gestor_id) REFERENCES usuarios (id),
    CONSTRAINT ck_insights_tipo CHECK (tipo IN ('ALERTA_CUSTO', 'ALERTA_VENDA', 'RESUMO_GERAL', 'SUGESTAO_COMPRA', 'SUGESTAO_PRODUCAO'))
);

CREATE INDEX idx_clientes_gestor ON clientes (gestor_id);
CREATE INDEX idx_fornecedores_gestor ON fornecedores (gestor_id);
CREATE INDEX idx_produtos_gestor ON produtos (gestor_id);
CREATE INDEX idx_materias_primas_gestor ON materias_primas (gestor_id);
CREATE INDEX idx_lancamentos_gestor_data ON lancamentos (gestor_id, data_lancamento DESC);
CREATE INDEX idx_vendas_gestor_data ON vendas (gestor_id, data_venda DESC);
CREATE INDEX idx_compras_gestor_data ON compras_materias_primas (gestor_id, data_compra DESC);
CREATE INDEX idx_producoes_gestor_data ON producoes (gestor_id, data_producao DESC);
CREATE INDEX idx_insights_gestor_criado ON insights (gestor_id, criado_em DESC);
