CREATE TABLE empresas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

INSERT INTO empresas (nome, criado_em)
VALUES ('Empresa principal', CURRENT_TIMESTAMP);

ALTER TABLE usuarios ADD COLUMN empresa_id BIGINT;

UPDATE usuarios
SET empresa_id = (SELECT MIN(id) FROM empresas)
WHERE empresa_id IS NULL;

-- Os registros iniciais eram globais, mas possuem estoque, custo e preço mutáveis.
-- Eles passam a pertencer à empresa principal para não compartilhar dados operacionais
-- entre tenants; gestores da mesma empresa continuam acessando o mesmo catálogo.
UPDATE materias_primas
SET gestor_id = (SELECT MIN(id) FROM usuarios)
WHERE gestor_id IS NULL;

UPDATE produtos
SET gestor_id = (SELECT MIN(id) FROM usuarios)
WHERE gestor_id IS NULL;

ALTER TABLE usuarios ALTER COLUMN empresa_id SET NOT NULL;
ALTER TABLE usuarios
    ADD CONSTRAINT fk_usuarios_empresa FOREIGN KEY (empresa_id) REFERENCES empresas (id);

CREATE INDEX idx_usuarios_empresa ON usuarios (empresa_id);
