CREATE TABLE importacoes_legadas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gestor_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    arquivo_principal VARCHAR(180),
    arquivos_analisados INTEGER NOT NULL,
    registros_analisados BIGINT NOT NULL,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalizado_em TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_importacoes_legadas_gestor FOREIGN KEY (gestor_id) REFERENCES usuarios (id),
    CONSTRAINT ck_importacoes_legadas_status CHECK (status IN ('SIMULACAO', 'EM_EXECUCAO', 'CONCLUIDA', 'FALHA'))
);

CREATE TABLE registros_importacao_legada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    importacao_id BIGINT NOT NULL,
    gestor_id BIGINT NOT NULL,
    arquivo VARCHAR(180) NOT NULL,
    linha INTEGER NOT NULL,
    codigo_legado VARCHAR(120),
    dominio VARCHAR(40) NOT NULL,
    classificacao VARCHAR(40),
    status VARCHAR(30) NOT NULL,
    entidade_tipo VARCHAR(80),
    entidade_id BIGINT,
    mensagem VARCHAR(1000),
    observacao VARCHAR(500),
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_registros_importacao_importacao FOREIGN KEY (importacao_id) REFERENCES importacoes_legadas (id),
    CONSTRAINT fk_registros_importacao_gestor FOREIGN KEY (gestor_id) REFERENCES usuarios (id),
    CONSTRAINT ck_registros_importacao_status CHECK (status IN ('IMPORTADO', 'NAO_IMPORTADO', 'PENDENTE', 'ERRO', 'AGUARDANDO_HISTORICO')),
    CONSTRAINT uk_registros_importacao_origem UNIQUE (gestor_id, arquivo, linha, codigo_legado, dominio)
);

CREATE INDEX idx_importacoes_legadas_gestor_criado
    ON importacoes_legadas (gestor_id, criado_em DESC);
CREATE INDEX idx_registros_importacao_execucao
    ON registros_importacao_legada (importacao_id, status);
CREATE INDEX idx_registros_importacao_origem
    ON registros_importacao_legada (gestor_id, arquivo, linha);

ALTER TABLE importacoes_legadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE registros_importacao_legada ENABLE ROW LEVEL SECURITY;

ALTER TABLE movimentacoes_estoque
    DROP CONSTRAINT ck_movimentacoes_origem;

ALTER TABLE movimentacoes_estoque
    ADD CONSTRAINT ck_movimentacoes_origem CHECK (
        origem IN ('CADASTRO', 'COMPRA', 'PRODUCAO', 'VENDA', 'AJUSTE_MANUAL', 'REMOCAO_MANUAL', 'MIGRACAO')
    );
