CREATE TABLE produto_gabarito_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade_necessaria NUMERIC(12,3) NOT NULL,
    materia_prima_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    CONSTRAINT fk_produto_gabarito_itens_materia_prima FOREIGN KEY (materia_prima_id) REFERENCES materias_primas (id),
    CONSTRAINT fk_produto_gabarito_itens_produto FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE INDEX idx_produto_gabarito_itens_materia_prima ON produto_gabarito_itens (materia_prima_id);
CREATE INDEX idx_produto_gabarito_itens_produto ON produto_gabarito_itens (produto_id);
