CREATE TABLE produto_gabaritos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade_base NUMERIC(12,3) NOT NULL,
    observacao VARCHAR(500),
    produto_id BIGINT NOT NULL,
    CONSTRAINT uk_produto_gabaritos_produto UNIQUE (produto_id),
    CONSTRAINT fk_produto_gabaritos_produto FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

INSERT INTO produto_gabaritos (produto_id, quantidade_base)
SELECT DISTINCT pgi.produto_id, 1
FROM produto_gabarito_itens pgi
WHERE NOT EXISTS (
    SELECT 1 FROM produto_gabaritos pg WHERE pg.produto_id = pgi.produto_id
);

ALTER TABLE produto_gabarito_itens ADD COLUMN gabarito_id BIGINT;

UPDATE produto_gabarito_itens pgi
SET gabarito_id = pg.id
FROM produto_gabaritos pg
WHERE pg.produto_id = pgi.produto_id;

ALTER TABLE produto_gabarito_itens ALTER COLUMN gabarito_id SET NOT NULL;
ALTER TABLE produto_gabarito_itens
    ADD CONSTRAINT fk_produto_gabarito_itens_gabarito FOREIGN KEY (gabarito_id) REFERENCES produto_gabaritos (id);
ALTER TABLE produto_gabarito_itens DROP CONSTRAINT fk_produto_gabarito_itens_produto;
DROP INDEX idx_produto_gabarito_itens_produto;
ALTER TABLE produto_gabarito_itens DROP COLUMN produto_id;

CREATE INDEX idx_produto_gabarito_itens_gabarito ON produto_gabarito_itens (gabarito_id);
