CREATE TABLE movimentacoes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_item VARCHAR(20) NOT NULL,
    produto_id BIGINT,
    materia_prima_id BIGINT,
    item_nome VARCHAR(120) NOT NULL,
    unidade_medida VARCHAR(30) NOT NULL,
    tipo_movimentacao VARCHAR(20) NOT NULL,
    origem VARCHAR(30) NOT NULL,
    quantidade NUMERIC(12,3) NOT NULL,
    saldo_anterior NUMERIC(12,3) NOT NULL,
    saldo_posterior NUMERIC(12,3) NOT NULL,
    usuario_id BIGINT NOT NULL,
    observacao VARCHAR(500),
    ocorrido_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_movimentacoes_produto FOREIGN KEY (produto_id) REFERENCES produtos (id),
    CONSTRAINT fk_movimentacoes_materia_prima FOREIGN KEY (materia_prima_id) REFERENCES materias_primas (id),
    CONSTRAINT fk_movimentacoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_movimentacoes_tipo_item CHECK (tipo_item IN ('PRODUTO', 'MATERIA_PRIMA')),
    CONSTRAINT ck_movimentacoes_tipo CHECK (tipo_movimentacao IN ('ENTRADA', 'SAIDA', 'AJUSTE')),
    CONSTRAINT ck_movimentacoes_origem CHECK (origem IN ('CADASTRO', 'COMPRA', 'PRODUCAO', 'VENDA', 'AJUSTE_MANUAL')),
    CONSTRAINT ck_movimentacoes_item CHECK (
        (tipo_item = 'PRODUTO' AND produto_id IS NOT NULL AND materia_prima_id IS NULL)
        OR (tipo_item = 'MATERIA_PRIMA' AND materia_prima_id IS NOT NULL AND produto_id IS NULL)
    )
);

CREATE INDEX idx_movimentacoes_ocorrido ON movimentacoes_estoque (ocorrido_em DESC);
CREATE INDEX idx_movimentacoes_usuario_ocorrido ON movimentacoes_estoque (usuario_id, ocorrido_em DESC);
CREATE INDEX idx_movimentacoes_produto_ocorrido ON movimentacoes_estoque (produto_id, ocorrido_em DESC);
CREATE INDEX idx_movimentacoes_materia_ocorrido ON movimentacoes_estoque (materia_prima_id, ocorrido_em DESC);
CREATE INDEX idx_movimentacoes_tipo_ocorrido ON movimentacoes_estoque (tipo_movimentacao, ocorrido_em DESC);
