-- Categorias normalizadas e SKU opcionais mantêm compatibilidade com o catálogo legado.
CREATE TABLE categorias_produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    categoria_pai_id BIGINT,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_categoria_pai FOREIGN KEY (categoria_pai_id) REFERENCES categorias_produto (id),
    CONSTRAINT uk_categoria_nome UNIQUE (nome)
);

ALTER TABLE produtos ADD COLUMN sku VARCHAR(60);
ALTER TABLE produtos ADD COLUMN categoria_id BIGINT;
ALTER TABLE produtos ADD CONSTRAINT fk_produtos_categoria FOREIGN KEY (categoria_id) REFERENCES categorias_produto (id);
CREATE UNIQUE INDEX uk_produtos_sku_global ON produtos (LOWER(sku)) WHERE sku IS NOT NULL;
CREATE INDEX idx_produtos_categoria_nome ON produtos (categoria_id, nome);

CREATE TABLE historico_precos_produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    preco NUMERIC(12,2) NOT NULL,
    inicio_vigencia TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    fim_vigencia TIMESTAMP(6) WITHOUT TIME ZONE,
    usuario_id BIGINT,
    alterado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    motivo VARCHAR(500),
    origem VARCHAR(60) NOT NULL,
    CONSTRAINT fk_hist_preco_produto FOREIGN KEY (produto_id) REFERENCES produtos (id),
    CONSTRAINT fk_hist_preco_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE historico_custos_materia_prima (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materia_prima_id BIGINT NOT NULL,
    custo NUMERIC(12,2) NOT NULL,
    inicio_vigencia TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    fim_vigencia TIMESTAMP(6) WITHOUT TIME ZONE,
    usuario_id BIGINT,
    alterado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    motivo VARCHAR(500),
    origem VARCHAR(60) NOT NULL,
    CONSTRAINT fk_hist_custo_materia FOREIGN KEY (materia_prima_id) REFERENCES materias_primas (id),
    CONSTRAINT fk_hist_custo_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

INSERT INTO historico_precos_produto (produto_id, preco, inicio_vigencia, origem)
SELECT id, preco_venda, criado_em, 'MIGRACAO' FROM produtos;
INSERT INTO historico_custos_materia_prima (materia_prima_id, custo, inicio_vigencia, origem)
SELECT id, custo_medio, criado_em, 'MIGRACAO' FROM materias_primas;

ALTER TABLE itens_venda ADD COLUMN custo_considerado NUMERIC(12,2);
ALTER TABLE itens_venda ADD COLUMN desconto NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE itens_venda ADD COLUMN acrescimo NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE itens_compra_materia_prima ADD COLUMN desconto NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE itens_compra_materia_prima ADD COLUMN acrescimo NUMERIC(12,2) NOT NULL DEFAULT 0;

CREATE TABLE auditoria_operacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    ocorrido_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    entidade VARCHAR(80) NOT NULL,
    registro_id BIGINT,
    operacao VARCHAR(40) NOT NULL,
    valor_anterior TEXT,
    valor_novo TEXT,
    motivo VARCHAR(500),
    origem VARCHAR(80),
    referencia_tipo VARCHAR(80),
    referencia_id BIGINT,
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

-- Confirmados pelas listagens e filtros atuais: data, cliente/produto e ledger.
CREATE INDEX idx_vendas_data_id ON vendas (data_venda DESC, id DESC);
CREATE INDEX idx_vendas_cliente_data ON vendas (cliente_id, data_venda DESC);
CREATE INDEX idx_producoes_data_id ON producoes (data_producao DESC, id DESC);
CREATE INDEX idx_producoes_produto_data ON producoes (produto_id, data_producao DESC);
CREATE INDEX idx_movimentacoes_origem_ocorrido ON movimentacoes_estoque (origem, ocorrido_em DESC);
CREATE INDEX idx_hist_preco_produto_vigencia ON historico_precos_produto (produto_id, inicio_vigencia DESC);
CREATE INDEX idx_hist_custo_materia_vigencia ON historico_custos_materia_prima (materia_prima_id, inicio_vigencia DESC);
CREATE INDEX idx_auditoria_entidade_registro ON auditoria_operacoes (entidade, registro_id, ocorrido_em DESC);
