ALTER TABLE produtos ADD COLUMN custo_atual NUMERIC(12,2);

CREATE TABLE historico_custos_produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    custo NUMERIC(12,2) NOT NULL,
    inicio_vigencia TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    fim_vigencia TIMESTAMP(6) WITHOUT TIME ZONE,
    usuario_id BIGINT,
    alterado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    motivo VARCHAR(500),
    origem VARCHAR(60) NOT NULL,
    CONSTRAINT fk_hist_custo_produto FOREIGN KEY (produto_id) REFERENCES produtos (id),
    CONSTRAINT fk_hist_custo_produto_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX idx_hist_custo_produto_vigencia
    ON historico_custos_produto (produto_id, inicio_vigencia DESC);

-- Valores antigos permanecem nulos: o custo real das vendas passadas não pode ser reconstruído.
-- Novas vendas passam a registrar o custo_atual vigente no item.
