-- V26__add_venda_envio.sql
-- Registro estruturado da forma de envio de cada venda.

CREATE TABLE envios_venda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id BIGINT NOT NULL UNIQUE,
    forma_envio VARCHAR(20) NOT NULL,
    custo_envio NUMERIC(12,2),
    responsavel_entrega VARCHAR(120),
    data_envio DATE,
    previsao_entrega DATE,
    codigo_rastreamento VARCHAR(120),

    transportadora_nome VARCHAR(160),
    transportadora_cnpj VARCHAR(20),
    transportadora_telefone VARCHAR(30),
    transportadora_email VARCHAR(160),
    transportadora_cep VARCHAR(12),
    transportadora_endereco VARCHAR(180),
    transportadora_numero VARCHAR(20),
    transportadora_complemento VARCHAR(120),
    transportadora_bairro VARCHAR(100),
    transportadora_cidade VARCHAR(100),
    transportadora_estado VARCHAR(2),
    observacao TEXT,

    CONSTRAINT fk_envios_venda_venda
        FOREIGN KEY (venda_id) REFERENCES vendas(id) ON DELETE CASCADE,
    CONSTRAINT ck_envios_venda_forma
        CHECK (forma_envio IN ('RETIRADA', 'PROPRIO', 'TRANSPORTADORA')),
    CONSTRAINT ck_envios_venda_custo
        CHECK (custo_envio IS NULL OR custo_envio >= 0)
);

CREATE INDEX idx_envios_venda_forma ON envios_venda (forma_envio);
CREATE INDEX idx_envios_venda_rastreamento ON envios_venda (codigo_rastreamento);
