/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as ProducaoRouteImport } from './routes/producao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AReceberRouteImport } from './routes/a-receber'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrarIndexRouteImport } from './routes/registrar.index'
import { Route as RegistrarVendaRouteImport } from './routes/registrar.venda'
import { Route as RegistrarProducaoRouteImport } from './routes/registrar.producao'
import { Route as RegistrarGastosRouteImport } from './routes/registrar.gastos'
import { Route as RegistrarCompraRouteImport } from './routes/registrar.compra'
import { Route as ProducaoIdRouteImport } from './routes/producao.$id'
import { Route as ProducaoHistoricoFamiliaRouteImport } from './routes/producao.historico.$familia'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AReceberRoute = AReceberRouteImport.update({
  id: '/a-receber',
  path: '/a-receber',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarIndexRoute = RegistrarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistrarRoute,
} as any)
const RegistrarVendaRoute = RegistrarVendaRouteImport.update({
  id: '/venda',
  path: '/venda',
  getParentRoute: () => RegistrarRoute,
} as any)
const RegistrarProducaoRoute = RegistrarProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => RegistrarRoute,
} as any)
const RegistrarGastosRoute = RegistrarGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => RegistrarRoute,
} as any)
const RegistrarCompraRoute = RegistrarCompraRouteImport.update({
  id: '/compra',
  path: '/compra',
  getParentRoute: () => RegistrarRoute,
} as any)
const ProducaoIdRoute = ProducaoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProducaoRoute,
} as any)
const ProducaoHistoricoFamiliaRoute =
  ProducaoHistoricoFamiliaRouteImport.update({
    id: '/historico/$familia',
    path: '/historico/$familia',
    getParentRoute: () => ProducaoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-receber': typeof AReceberRoute
  '/clientes': typeof ClientesRoute
  '/estoque': typeof EstoqueRoute
  '/gastos': typeof GastosRoute
  '/login': typeof LoginRoute
  '/producao': typeof ProducaoRouteWithChildren
  '/registrar': typeof RegistrarRouteWithChildren
  '/vendas': typeof VendasRoute
  '/producao/$id': typeof ProducaoIdRoute
  '/registrar/compra': typeof RegistrarCompraRoute
  '/registrar/gastos': typeof RegistrarGastosRoute
  '/registrar/producao': typeof RegistrarProducaoRoute
  '/registrar/venda': typeof RegistrarVendaRoute
  '/registrar/': typeof RegistrarIndexRoute
  '/producao/historico/$familia': typeof ProducaoHistoricoFamiliaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-receber': typeof AReceberRoute
  '/clientes': typeof ClientesRoute
  '/estoque': typeof EstoqueRoute
  '/gastos': typeof GastosRoute
  '/login': typeof LoginRoute
  '/producao': typeof ProducaoRouteWithChildren
  '/vendas': typeof VendasRoute
  '/producao/$id': typeof ProducaoIdRoute
  '/registrar/compra': typeof RegistrarCompraRoute
  '/registrar/gastos': typeof RegistrarGastosRoute
  '/registrar/producao': typeof RegistrarProducaoRoute
  '/registrar/venda': typeof RegistrarVendaRoute
  '/registrar': typeof RegistrarIndexRoute
  '/producao/historico/$familia': typeof ProducaoHistoricoFamiliaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-receber': typeof AReceberRoute
  '/clientes': typeof ClientesRoute
  '/estoque': typeof EstoqueRoute
  '/gastos': typeof GastosRoute
  '/login': typeof LoginRoute
  '/producao': typeof ProducaoRouteWithChildren
  '/registrar': typeof RegistrarRouteWithChildren
  '/vendas': typeof VendasRoute
  '/producao/$id': typeof ProducaoIdRoute
  '/registrar/compra': typeof RegistrarCompraRoute
  '/registrar/gastos': typeof RegistrarGastosRoute
  '/registrar/producao': typeof RegistrarProducaoRoute
  '/registrar/venda': typeof RegistrarVendaRoute
  '/registrar/': typeof RegistrarIndexRoute
  '/producao/historico/$familia': typeof ProducaoHistoricoFamiliaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-receber'
    | '/clientes'
    | '/estoque'
    | '/gastos'
    | '/login'
    | '/producao'
    | '/registrar'
    | '/vendas'
    | '/producao/$id'
    | '/registrar/compra'
    | '/registrar/gastos'
    | '/registrar/producao'
    | '/registrar/venda'
    | '/registrar/'
    | '/producao/historico/$familia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-receber'
    | '/clientes'
    | '/estoque'
    | '/gastos'
    | '/login'
    | '/producao'
    | '/vendas'
    | '/producao/$id'
    | '/registrar/compra'
    | '/registrar/gastos'
    | '/registrar/producao'
    | '/registrar/venda'
    | '/registrar'
    | '/producao/historico/$familia'
  id:
    | '__root__'
    | '/'
    | '/a-receber'
    | '/clientes'
    | '/estoque'
    | '/gastos'
    | '/login'
    | '/producao'
    | '/registrar'
    | '/vendas'
    | '/producao/$id'
    | '/registrar/compra'
    | '/registrar/gastos'
    | '/registrar/producao'
    | '/registrar/venda'
    | '/registrar/'
    | '/producao/historico/$familia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AReceberRoute: typeof AReceberRoute
  ClientesRoute: typeof ClientesRoute
  EstoqueRoute: typeof EstoqueRoute
  GastosRoute: typeof GastosRoute
  LoginRoute: typeof LoginRoute
  ProducaoRoute: typeof ProducaoRouteWithChildren
  RegistrarRoute: typeof RegistrarRouteWithChildren
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-receber': {
      id: '/a-receber'
      path: '/a-receber'
      fullPath: '/a-receber'
      preLoaderRoute: typeof AReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar/': {
      id: '/registrar/'
      path: '/'
      fullPath: '/registrar/'
      preLoaderRoute: typeof RegistrarIndexRouteImport
      parentRoute: typeof RegistrarRoute
    }
    '/registrar/venda': {
      id: '/registrar/venda'
      path: '/venda'
      fullPath: '/registrar/venda'
      preLoaderRoute: typeof RegistrarVendaRouteImport
      parentRoute: typeof RegistrarRoute
    }
    '/registrar/producao': {
      id: '/registrar/producao'
      path: '/producao'
      fullPath: '/registrar/producao'
      preLoaderRoute: typeof RegistrarProducaoRouteImport
      parentRoute: typeof RegistrarRoute
    }
    '/registrar/gastos': {
      id: '/registrar/gastos'
      path: '/gastos'
      fullPath: '/registrar/gastos'
      preLoaderRoute: typeof RegistrarGastosRouteImport
      parentRoute: typeof RegistrarRoute
    }
    '/registrar/compra': {
      id: '/registrar/compra'
      path: '/compra'
      fullPath: '/registrar/compra'
      preLoaderRoute: typeof RegistrarCompraRouteImport
      parentRoute: typeof RegistrarRoute
    }
    '/producao/$id': {
      id: '/producao/$id'
      path: '/$id'
      fullPath: '/producao/$id'
      preLoaderRoute: typeof ProducaoIdRouteImport
      parentRoute: typeof ProducaoRoute
    }
    '/producao/historico/$familia': {
      id: '/producao/historico/$familia'
      path: '/historico/$familia'
      fullPath: '/producao/historico/$familia'
      preLoaderRoute: typeof ProducaoHistoricoFamiliaRouteImport
      parentRoute: typeof ProducaoRoute
    }
  }
}

interface ProducaoRouteChildren {
  ProducaoIdRoute: typeof ProducaoIdRoute
  ProducaoHistoricoFamiliaRoute: typeof ProducaoHistoricoFamiliaRoute
}

const ProducaoRouteChildren: ProducaoRouteChildren = {
  ProducaoIdRoute: ProducaoIdRoute,
  ProducaoHistoricoFamiliaRoute: ProducaoHistoricoFamiliaRoute,
}

const ProducaoRouteWithChildren = ProducaoRoute._addFileChildren(
  ProducaoRouteChildren,
)

interface RegistrarRouteChildren {
  RegistrarCompraRoute: typeof RegistrarCompraRoute
  RegistrarGastosRoute: typeof RegistrarGastosRoute
  RegistrarProducaoRoute: typeof RegistrarProducaoRoute
  RegistrarVendaRoute: typeof RegistrarVendaRoute
  RegistrarIndexRoute: typeof RegistrarIndexRoute
}

const RegistrarRouteChildren: RegistrarRouteChildren = {
  RegistrarCompraRoute: RegistrarCompraRoute,
  RegistrarGastosRoute: RegistrarGastosRoute,
  RegistrarProducaoRoute: RegistrarProducaoRoute,
  RegistrarVendaRoute: RegistrarVendaRoute,
  RegistrarIndexRoute: RegistrarIndexRoute,
}

const RegistrarRouteWithChildren = RegistrarRoute._addFileChildren(
  RegistrarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AReceberRoute: AReceberRoute,
  ClientesRoute: ClientesRoute,
  EstoqueRoute: EstoqueRoute,
  GastosRoute: GastosRoute,
  LoginRoute: LoginRoute,
  ProducaoRoute: ProducaoRouteWithChildren,
  RegistrarRoute: RegistrarRouteWithChildren,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
