package com.InovaSkill.CaderninhoDigital.ai.contract;

public enum FerramentaPermitida {
    RESUMO_OPERACIONAL,
    RESUMO_ESTOQUE,
    RESUMO_VENDAS,
    RESUMO_GASTOS,
    RESUMO_COMPRAS,
    ANALISE_CUSTO_PRODUTO,
    ANALISE_COMPRAS_INSUMO,
    COMPARAR_PRECO_MERCADO,
    RESUMO_PRODUCAO,
    RESUMO_RECEBIVEIS
}
