package com.InovaSkill.CaderninhoDigital.ai.contract;

public enum IntencaoOrquestrador {
    RESUMO_NEGOCIO,
    CONSULTAR_ESTOQUE,
    CONSULTAR_VENDAS,
    CONSULTAR_GASTOS,
    CONSULTAR_COMPRAS,
    ANALISAR_CUSTO_PRODUTO,
    ANALISAR_MARGEM_PRODUTO,
    ANALISAR_RENTABILIDADE_PRODUTO,
    ANALISAR_COMPRAS_INSUMO,
    COMPARAR_PRECO_MERCADO,
    CONSULTAR_PRODUCAO,
    CONSULTAR_RECEBIVEIS,
    COMPARAR_VENDAS_GASTOS,
    COMPARAR_VENDAS_PERIODOS,
    ANALISE_EMPRESARIAL,
    DESCONHECIDA
}
